### ISSUE TITLE
The title sequences should have parks that don't use RLE

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/title-sequences#8]
Disabling RLE in SV6 yields 22% smaller size, or just about 1MiB less, when compressed with zip later, as tested on my system. That should help reducing size of produced binaries of OpenRCT2.

**Comment by janisozaur** [comment]
I will submit recompressed parks later.

**Comment by Gymnasiast** [comment]
Can vanilla load non-RLE compressed parks?

**Comment by janisozaur** [comment]
Yes, it should

**Comment by janisozaur** [comment]
[titleseq.zip](https://github.com/OpenRCT2/title-sequences/files/3322557/titleseq.zip)


@Gymnasiast can you take care of testing with vanilla and releasing it?

**Comment by Gymnasiast** [comment]
Four of the parks show an error trapper when loading in vanilla. However, I have a hunch that this is not because they lack RLE encoding.

The rest loads fine.

**Comment by janisozaur** [comment]
Thanks. GitHub says the resulting zip shrunk from 3.88MB to 3.14MB, a 19% reduction.

**Comment by susnux** [comment]
That titles.zip (same as the one provided in the release section of this GH page) does not include the other titles, just the openrct version.
